org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.java.installations.auto-download=false

minecraft_version=1.12.2

forge_gradle_version=6.0.+
forge_version=14.23.5.2860
mappings_channel=stable
mappings_version=39-1.12

mixin_gradle_version=0.7.+
mixin_version=0.8.5

shadow_gradle_version=8.1.1

mod_id=betterbiomeblendcontinued
mod_name=Better Biomer Blend Continued
mod_group=michaelsebero.betterbiomeblend
mod_version=1.2.0
mod_author=["]
mod_description=

mixin_loader_class=michaelsebero.betterbiomeblend.BetterBiomeBlendPlugin
